server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lebronjames_kobe
          search-paths: spring-cloud-config-server/config-repo
          username: 3162310162@qq.com
          password: zhipaiwu
#配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.5.2.241:1111/eureka/            